export { HeroSection } from "./HeroSection"
export { FeaturesSection } from "./FeaturesSection"
export { PlansSection } from "./PlansSection"
export { InstagramSection } from "./InstagramSection"
export { ChoosePlanSection } from "./ChoosePlanSection"